const adventures = [
{
  "name": "00148",
  "fname": "00148TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/148.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/148.jpg"
},
{
  "name": "00147",
  "fname": "00147TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/147.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/147.jpg"
},
{
  "name": "00146",
  "fname": "00146TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/146.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/146.jpg"
},
{
  "name": "00145",
  "fname": "00145TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/145.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/145.jpg"
},
{
  "name": "00144",
  "fname": "00144TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/144.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/144.jpg"
},
{
  "name": "00143",
  "fname": "00143TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/143.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/143.jpg"
},
{
  "name": "00141",
  "fname": "00141TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/141.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/141.jpg"
},
{
  "name": "00139",
  "fname": "00139TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/139.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/139.jpg"
},
{
  "name": "00138",
  "fname": "00138TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/138.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/138.jpg"
},
{
  "name": "00137",
  "fname": "00137TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/137.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/137.jpg"
},
{
  "name": "00136",
  "fname": "00136TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/136.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/136.jpg"
},
{
  "name": "00135",
  "fname": "00135TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/135.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/135.jpg"
},
{
  "name": "00134",
  "fname": "00134TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/134.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/134.jpg"
},
{
  "name": "00133",
  "fname": "00133TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/133.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/133.jpg"
},
{
  "name": "00132",
  "fname": "00132TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/132.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/132.jpg"
},
{
  "name": "00131",
  "fname": "00131TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/131.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/131.jpg"
},
{
  "name": "00129",
  "fname": "00129TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/129.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/129.jpg"
},
{
  "name": "00128",
  "fname": "00128TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/128.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/128.jpg"
},
{
  "name": "00124",
  "fname": "00124TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/124.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/124.jpg"
},
{
  "name": "00122",
  "fname": "00122TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/122.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/122.jpg"
},
{
  "name": "00119",
  "fname": "00119TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/119.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/119.jpg"
},
{
  "name": "00118",
  "fname": "00118TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/118.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/118.jpg"
},
{
  "name": "00108",
  "fname": "00108TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/108.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/108.jpg"
},
{
  "name": "00107",
  "fname": "00107TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/107.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/107.jpg"
},
{
  "name": "016",
  "fname": "016TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/016.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/016.jpg"
},
{
  "name": "0014",
  "fname": "0014TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/0014.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/0014.jpg"
},
{
  "name": "0013",
  "fname": "0013TW0204",
  "category": "Teen Walk",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Teenwalk/0013.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Teenwalk/0013.jpg"
},
{
  "name": "00392",
  "fname": "00392ll0204",
  "category": "Lalana",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Lalana/392.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Lalana/392.jpg"
},
{
  "name": "00390",
  "fname": "00390ll0204",
  "category": "Lalana",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Lalana/390.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Lalana/390.jpg"
},
{
  "name": "00385",
  "fname": "00385ll0204",
  "category": "Lalana",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Lalana/385.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Lalana/385.jpg"
},
{
  "name": "00382",
  "fname": "00382ll0204",
  "category": "Lalana",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Lalana/382.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Lalana/382.jpg"
},
{
  "name": "00386",
  "fname": "00386ll0204",
  "category": "Lalana",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Lalana/386.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Lalana/386.jpg"
},
{
  "name": "00388",
  "fname": "00388ll0204",
  "category": "Lalana",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Lalana/388.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Lalana/388.jpg"
},
{
  "name": "00391",
  "fname": "00391ll0204",
  "category": "Lalana",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Lalana/391.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Lalana/391.jpg"
},
{
  "name": "01612",
  "fname": "01612SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1612.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1612.jpg"
},
{
  "name": "01673",
  "fname": "01673SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1673.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1673.jpg"
},
{
  "name": "01614",
  "fname": "01614SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1614.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1614.jpg"
},
{
  "name": "01675",
  "fname": "01675SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1675.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1675.jpg"
},
{
  "name": "01619",
  "fname": "01619SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1619.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1619.jpg"
},
{
  "name": "01678",
  "fname": "01678SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1678.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1678.jpg"
},
{
  "name": "01626",
  "fname": "01626SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1626.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1626.jpg"
},
{
  "name": "01679",
  "fname": "01679SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1679.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1679.jpg"
},
{
  "name": "01642",
  "fname": "01642SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1642.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1642.jpg"
},
{
  "name": "01682",
  "fname": "01682SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1682.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1682.jpg"
},
{
  "name": "01644",
  "fname": "01644SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1644.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1644.jpg"
},
{
  "name": "01685",
  "fname": "01685SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1685.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1685.jpg"
},
{
  "name": "01650",
  "fname": "01650SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1650.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1650.jpg"
},
{
  "name": "01688",
  "fname": "01688SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1688.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1688.jpg"
},
{
  "name": "01651",
  "fname": "01651SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1651.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1651.jpg"
},
{
  "name": "01690",
  "fname": "01690SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1690.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1690.jpg"
},
{
  "name": "01654",
  "fname": "01654SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1654.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1654.jpg"
},
{
  "name": "01691",
  "fname": "01691SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1691.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1691.jpg"
},
{
  "name": "01659",
  "fname": "01659SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1659.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1659.jpg"
},
{
  "name": "01693",
  "fname": "01693SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1693.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1693.jpg"
},
{
  "name": "01661",
  "fname": "01661SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1661.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1661.jpg"
},
{
  "name": "01664",
  "fname": "01664SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1664.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1664.jpg"
},
{
  "name": "01665",
  "fname": "01665SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1665.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1665.jpg"
},
{
  "name": "01666",
  "fname": "01666SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1666.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1666.jpg"
},
{
  "name": "01667",
  "fname": "01667SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1667.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1667.jpg"
},
{
  "name": "01669",
  "fname": "01669SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1669.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1669.jpg"
},
{
  "name": "01672",
  "fname": "01672SL0204",
  "category": "Style PU",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style PU/1672.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style PU/1672.jpg"
},
{
  "name": "01571",
  "fname": "01571SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1571.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1571.jpg"
},
{
  "name": "01681",
  "fname": "01681SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1681.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1681.jpg"
},
{
  "name": "01613",
  "fname": "01613SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1613.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1613.jpg"
},
{
  "name": "01684",
  "fname": "01684SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1684.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1684.jpg"
},
{
  "name": "01628",
  "fname": "01628SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1628.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1628.jpg"
},
{
  "name": "01686",
  "fname": "01686SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1686.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1686.jpg"
},
{
  "name": "01634",
  "fname": "01634SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1634.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1634.jpg"
},
{
  "name": "01687",
  "fname": "01687SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1687.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1687.jpg"
},
{
  "name": "01635",
  "fname": "01635SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1635.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1635.jpg"
},
{
  "name": "01637",
  "fname": "01637SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1637.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1637.jpg"
},
{
  "name": "01638",
  "fname": "01638SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1638.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1638.jpg"
},
{
  "name": "01640",
  "fname": "01640SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1640.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1640.jpg"
},
{
  "name": "01646",
  "fname": "01646SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1646.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1646.jpg"
},
{
  "name": "01649",
  "fname": "01649SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1649.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1649.jpg"
},
{
  "name": "01652",
  "fname": "01652SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1652.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1652.jpg"
},
{
  "name": "01653",
  "fname": "01653SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1653.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1653.jpg"
},
{
  "name": "01657",
  "fname": "01657SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1657.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1657.jpg"
},
{
  "name": "01662",
  "fname": "01662SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1662.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1662.jpg"
},
{
  "name": "01668",
  "fname": "01668SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1668.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1668.jpg"
},
{
  "name": "01670",
  "fname": "01670SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1670.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1670.jpg"
},
{
  "name": "01680",
  "fname": "01680SL0204",
  "category": "Style Shining",
  "colors": "Black | Pink | Beidge",
  "sizes": "4 5 6 7 8",
  "forthe": "Women",
  "image": "source/Style Shining/1680.jpg",
  "link": "template.html",
  "status": "View Image",
  "Stock": "Stock Available",
  "New_item": "",
  "Date": "2025-09-29",
  "price": "N/A",
  "extraimage1": "source/Style Shining/1680.jpg"
},
  {
    "name": "00192",
    "fname": "00192sc0201",
    "category": "Children",
    "colors": "Black | Pink | Beidge",
    "sizes": "4 5 6 7 8",
    "forthe": "Women",
    "image": "source/Children/192.jpg",
    "link": "template.html",
    "status": "View Image",
    "Stock": "Stock Available",
    "New_item": "",
    "Date": "2025-09-29",
    "price": "N/A",
    "extraimage1": "source/Children/192.jpg"
  },
  {
    "name": "00193",
    "fname": "00193sc0201",
    "category": "Children",
    "colors": "Black | Pink | Beidge",
    "sizes": "4 5 6 7 8",
    "forthe": "Women",
    "image": "source/Children/193.jpg",
    "link": "template.html",
    "status": "View Image",
    "Stock": "Stock Available",
    "New_item": "",
    "Date": "2025-09-29",
    "price": "N/A",
    "extraimage1": "source/Children/193.jpg"
  },
  {
    "name": "00194",
    "fname": "00194sc0201",
    "category": "Children",
    "colors": "Black | Pink | Beidge",
    "sizes": "4 5 6 7 8",
    "forthe": "Women",
    "image": "source/Children/194.jpg",
    "link": "template.html",
    "status": "View Image",
    "Stock": "Stock Available",
    "New_item": "",
    "Date": "2025-09-29",
    "price": "N/A",
    "extraimage1": "source/Children/194.jpg"
  },
  {
    "name": "00195",
    "fname": "00195sc0201",
    "category": "Children",
    "colors": "Black | Pink | Beidge",
    "sizes": "4 5 6 7 8",
    "forthe": "Women",
    "image": "source/Children/195.jpg",
    "link": "template.html",
    "status": "View Image",
    "Stock": "Stock Available",
    "New_item": "",
    "Date": "2025-09-29",
    "price": "N/A",
    "extraimage1": "source/Children/195.jpg"
  },
  {
    "name": "00196",
    "fname": "00196sc0201",
    "category": "Children",
    "colors": "Black | Pink | Beidge",
    "sizes": "4 5 6 7 8",
    "forthe": "Women",
    "image": "source/Children/196.jpg",
    "link": "template.html",
    "status": "View Image",
    "Stock": "Stock Available",
    "New_item": "",
    "Date": "2025-09-29",
    "price": "N/A",
    "extraimage1": "source/Children/196.jpg"
  },
  {
    "name": "00197",
    "fname": "00197sc0201",
    "category": "Children",
    "colors": "Black | Pink | Beidge",
    "sizes": "4 5 6 7 8",
    "forthe": "Women",
    "image": "source/Children/197.jpg",
    "link": "template.html",
    "status": "View Image",
    "Stock": "Stock Available",
    "New_item": "",
    "Date": "2025-09-29",
    "price": "N/A",
    "extraimage1": "source/Children/197.jpg"
  },
  {
    "name": "00198",
    "fname": "00198sc0201",
    "category": "Children",
    "colors": "Black | Pink | Beidge",
    "sizes": "4 5 6 7 8",
    "forthe": "Women",
    "image": "source/Children/198.jpg",
    "link": "template.html",
    "status": "View Image",
    "Stock": "Stock Available",
    "New_item": "",
    "Date": "2025-09-29",
    "price": "N/A",
    "extraimage1": "source/Children/198.jpg"
  },
  {
    "name": "00201",
    "fname": "00201sc0201",
    "category": "Children",
    "colors": "Black | Pink | Beidge",
    "sizes": "4 5 6 7 8",
    "forthe": "Women",
    "image": "source/Children/201.jpg",
    "link": "template.html",
    "status": "View Image",
    "Stock": "Stock Available",
    "New_item": "",
    "Date": "2025-09-29",
    "price": "N/A",
    "extraimage1": "source/Children/201.jpg"
  },
  {
    "name": "00202",
    "fname": "00202sc0201",
    "category": "Children",
    "colors": "Black | Pink | Beidge",
    "sizes": "4 5 6 7 8",
    "forthe": "Women",
    "image": "source/Children/202.jpg",
    "link": "template.html",
    "status": "View Image",
    "Stock": "Stock Available",
    "New_item": "",
    "Date": "2025-09-29",
    "price": "N/A",
    "extraimage1": "source/Children/202.jpg"
  },
  {
    "name": "00203",
    "fname": "00203sc0201",
    "category": "Children",
    "colors": "Black | Pink | Beidge",
    "sizes": "4 5 6 7 8",
    "forthe": "Women",
    "image": "source/Children/203.jpg",
    "link": "template.html",
    "status": "View Image",
    "Stock": "Stock Available",
    "New_item": "",
    "Date": "2025-09-29",
    "price": "N/A",
    "extraimage1": "source/Children/203.jpg"
  },
  {
    "name": "00204",
    "fname": "00204sc0201",
    "category": "Children",
    "colors": "Black | Pink | Beidge",
    "sizes": "4 5 6 7 8",
    "forthe": "Women",
    "image": "source/Children/204.jpg",
    "link": "template.html",
    "status": "View Image",
    "Stock": "Stock Available",
    "New_item": "",
    "Date": "2025-09-29",
    "price": "N/A",
    "extraimage1": "source/Children/204.jpg"
  }

];
